# Library Import

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv("../Dataset/data.csv")
dataset.head(10)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,12592454,JF113025,1/14/2022 15:55,067XX S MORGAN ST,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,RESIDENCE,False,True,...,16.0,68,26,1170805.0,1860170.0,2022,9/14/2023 15:41,41.771782,-87.649437,"(41.771782439, -87.649436929)"
1,12785595,JF346553,8/5/2022 21:00,072XX S UNIVERSITY AVE,1544,SEX OFFENSE,SEXUAL EXPLOITATION OF A CHILD,APARTMENT,True,False,...,5.0,69,17,1185135.0,1857211.0,2022,9/14/2023 15:41,41.763338,-87.597001,"(41.763337967, -87.597001131)"
2,12808281,JF373517,8/14/2022 14:00,055XX W ARDMORE AVE,1562,SEX OFFENSE,AGGRAVATED CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,...,39.0,11,17,1138383.0,1937953.0,2022,9/14/2023 15:41,41.985875,-87.766404,"(41.985875279, -87.766403857)"
3,12888104,JF469015,11/10/2022 3:47,072XX S MAY ST,1477,WEAPONS VIOLATION,RECKLESS FIREARM DISCHARGE,STREET,False,False,...,17.0,68,15,1169903.0,1856822.0,2022,9/14/2023 15:41,41.762615,-87.652840,"(41.76261474, -87.652840463)"
4,13209277,JG422539,8/15/2022 9:00,0000X W JACKSON BLVD,810,THEFT,OVER $500,COMMERCIAL / BUSINESS OFFICE,False,False,...,4.0,32,6,NaN,NaN,2022,9/14/2023 15:43,NaN,NaN,NaN
5,12622465,JF149923,2/19/2022 10:36,010XX N FRANCISCO AVE,486,BATTERY,DOMESTIC BATTERY SIMPLE,HOSPITAL BUILDING / GROUNDS,True,True,...,26.0,24,08B,1156861.0,1906972.0,2022,9/15/2023 15:41,41.900506,-87.699285,"(41.900505589, -87.699285044)"
6,12640859,JF172230,3/13/2022 5:15,012XX W PRATT BLVD,486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,True,True,...,49.0,1,08B,1166646.0,1945317.0,2022,9/15/2023 15:41,42.005522,-87.662241,"(42.00552183, -87.662241448)"
7,12667337,JF203985,4/10/2022 21:38,011XX N CHERRY AVE,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,WAREHOUSE,True,True,...,27.0,8,26,1169620.0,1907431.0,2022,9/15/2023 15:41,41.901497,-87.652407,"(41.901496787, -87.652407386)"
8,12671049,JF208259,4/14/2022 22:10,003XX E OHIO ST,486,BATTERY,DOMESTIC BATTERY SIMPLE,VEHICLE - COMMERCIAL,True,True,...,2.0,8,08B,1178915.0,1904276.0,2022,9/15/2023 15:41,41.892632,-87.618363,"(41.892631803, -87.618362824)"
9,12678035,JF216671,4/22/2022 23:30,044XX N BROADWAY,810,THEFT,OVER $500,APARTMENT,True,True,...,46.0,3,6,1168614.0,1929562.0,2022,9/15/2023 15:41,41.962247,-87.655460,"(41.962247182, -87.6554598)"

# Basic Stats

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239558 entries, 0 to 239557
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    239558 non-null  int64
 1   Case Number           239558 non-null  object
 2   Date                  239558 non-null  object
 3   Block                 239558 non-null  object
 4   IUCR                  239558 non-null  object
 5   Primary Type          239558 non-null  object
 6   Description           239558 non-null  object
 7   Location Description  238593 non-null  object
 8   Arrest                239558 non-null  bool
 9   Domestic              239558 non-null  bool
 10  Beat                  239558 non-null  int64
 11  District              239558 non-null  int64
 12  Ward                  239548 non-null  float64
 13  Community Area        239558 non-null  int64
 14  FBI Code              239558 non-null  object
 15  X Coordinate          234891 non-null  float64
 16  Y Coordinate          234891 non-null  float64
 17  Year                  239558 non-null  int64
 18  Updated On            239558 non-null  object
 19  Latitude              234891 non-null  float64
 20  Longitude             234891 non-null  float64
 21  Location              234891 non-null  object
dtypes: bool(2), float64(5), int64(5), object(10)
memory usage: 37.0+ MB

In [4]:
dataset.describe()

,ID,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
count,2.395580e+05,239558.000000,239558.00000,239548.000000,239558.000000,2.348910e+05,2.348910e+05,239558.0,234891.000000,234891.000000
mean,1.273144e+07,1154.023276,11.31053,23.385029,36.268474,1.165381e+06,1.887038e+06,2022.0,41.845612,-87.668599
std,7.082019e+05,707.909870,7.07555,14.210565,21.553814,1.679375e+04,3.229564e+04,0.0,0.088833,0.061010
min,2.654300e+04,111.000000,1.00000,1.000000,1.000000,0.000000e+00,0.000000e+00,2022.0,36.619446,-91.686566
25%,1.267802e+07,533.000000,5.00000,9.000000,22.000000,1.153949e+06,1.859284e+06,2022.0,41.769168,-87.710150
50%,1.276893e+07,1033.000000,10.00000,24.000000,32.000000,1.167256e+06,1.893383e+06,2022.0,41.863073,-87.661465
75%,1.285704e+07,1731.000000,17.00000,35.000000,53.000000,1.176856e+06,1.910066e+06,2022.0,41.909023,-87.626402
max,1.363051e+07,2535.000000,31.00000,50.000000,77.000000,1.205119e+06,1.951493e+06,2022.0,42.022548,-87.524532